### ISSUE TITLE
Add "all" seasons to player endpoint

### ISSUE THREAD

**Issue by davshoward** [samdking/5aside#40] opened 2021-05-21 22:28 UTC
Is it possible to add an aggregated "all" seasons object in the player endpoint?

Either just add it under "seasons" named "all" or a new object titled something like "all_seasons".

**Comment by samdking** [comment] 2021-05-23 19:01
Duplicate of this I believe: https://github.com/samdking/5aside/issues/22

**Comment by davshoward** [comment] 2021-05-24 08:48
This would be for the player endpoint ideally. To output on the Selected Player page - would rather not have to call the seasons endpoint and then filter out all the matches without that player. 

I can aggregate all the seasons data into an ALL but thought it might be cleaner on the API?

**Comment by samdking** [comment] 2021-05-24 09:15
Ah, yep, good point. It will double the size of the endpoint, but I can appreciate that "all" data is missing which would be useful.

**Comment by davshoward** [comment] 2021-05-24 09:24
Could add it as a flag? 

players/10?show_all_seasons=1

Or something?

**Comment by samdking** [comment] 2021-05-24 12:46
Thinking about it, I remember making this decision intentionally. "All"  isn't considered a season, so doesn't appear under the "seasons" attribute. Streak data for all is top level, along with the cumulative scored, conceded, points totals. The only thing "all" doesn't have is results, as I deemed this to be too much repetition, when the individual seasons could just be combined to get all results.

**Comment by samdking** [comment] 2021-05-24 12:48
Scrap that, results are there for all 😆. So, basically, all the data you need is there I believe. It's just not listed under "seasons".

**Comment by samdking** [comment] 2021-05-24 12:50
So, to answer your original query.

All results: `player.results`
All streaks: `player.streaks`
All wins/losses/gd/etc. `player.<attribute>`

The same data for a specific season can be found at:

`player.seasons.<season>.<attribute>`

**Closed** 2021-08-03 13:46 UTC
Labels: new feature
